const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
if (!fs.existsSync(envPath)) {
  console.error('Error: .env file not found. Create one with GROQ_API_KEY=your_key');
  process.exit(1);
}

const env = fs.readFileSync(envPath, 'utf8');
const match = env.match(/^GROQ_API_KEY\s*=\s*(.+)$/m);
if (!match) {
  console.error('Error: GROQ_API_KEY not found in .env');
  process.exit(1);
}

const key = match[1].trim().replace(/^["']|["']$/g, '');
if (key === 'your_api_key_here' || key.length < 20) {
  console.error('Error: Replace "your_api_key_here" in .env with your real Groq API key.');
  process.exit(1);
}

const config = `// Auto-generated by setup.js — do not edit manually.\n// Edit .env then run: node setup.js\nconst GROQ_API_KEY = '${key}';\n`;
fs.writeFileSync(path.join(__dirname, 'config.js'), config);
console.log('✓ config.js updated successfully.');
